---
- name: SoftSys Set Up
  hosts: 127.0.0.1
  connection: local
  vars:
    git_user_name: "Your Name"
    git_user_email: "your.email@example.com"
    git_editor: "code"
    
  tasks:

  tasks:
    - name: Install required packages
      become: yes
      become_method: sudo
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - gcc
        - gdb
        - make
        - cmake
        - clang-format
        - clang-tidy
        - libcriterion-dev

    - name:
      command: git config --global core.editor "{{ git_editor }} --wait" 
      ignore_errors: # Ignore errors in case the core.editor is already set

    - name: Set Git user.name
      command: git config --global user.name "{{ git_user_name }}"
      ignore_errors: yes  # Ignore errors in case the user.name is already set

    - name: Set Git user.email
      command: git config --global user.email "{{ git_user_email }}"
      ignore_errors: yes  # Ignore errors in case the user.email is already set

    - name: Verify Git configuration
      command: git config --list | grep -E 'user.name|user.email'
      register: git_config_output
      changed_when: false  # Do not mark the task as changed if the configuration is already set

    - name: Install VSCode extensions
      ansible.builtin.shell: code --install-extension {{ item }}
      loop:
        - esbenp.prettier-vscode
        - ms-vscode.cpptools
        - ms-vscode.cmake-tools
        - xaver.clang-format
