on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - test

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    name: Test ansible playbook
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Ansible playbook
        uses: ./ # Uses an action in the root directory
        id: test-ansible-playbook
